version: "3.8"
services:
  backend:
    build:
      context: .  # Verwendet das aktuelle Verzeichnis (wo sich das Backend befindet)
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
    networks:
      - app-network

networks:
  app-network:
