
services:
  backend:
    build:
      context: ./  # Stelle sicher, dass der Pfad zum Backend korrekt ist
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
    networks:
      - app-network

  frontend:
    build:
      context: ./  # Stelle sicher, dass der Pfad zum Frontend korrekt ist
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
