services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: sudoku
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: .  # Hier das Root-Verzeichnis des Projekts (Sudoku)
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/sudoku
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    volumes:
      - ./backend:/app  # Der Ordner, der das Backend enth채lt
    working_dir: /app
    command: ["./gradlew", "bootRun"]
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend  # Ordner, der das Frontend enth채lt
      dockerfile: Dockerfile.dev  # Dockerfile f체r Dev-Umgebung
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app  # Ordner f체r das Frontend
      - /app/node_modules
    command: ["npm", "run", "dev"]
    environment:
      - VITE_API_URL=http://backend:8080
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
